### ISSUE TITLE
Model fidelity indicator in the Fidelity Chart missing bold border line for Aerodynamics

### ISSUE THREAD

**Issue by tensorgit** [IPG-Automotive-UK/react-ui#178]
![fidelity_graph](https://user-images.githubusercontent.com/76999529/119808086-13445b80-bee4-11eb-9329-25987ad848ab.JPG)
@dmbarry86

**Comment by dmbarry86** [comment]
This is raised in the wrong repo @tensorgit. Please raise it in VPM.
