### ISSUE TITLE
Add Header component

### ISSUE THREAD

**Issue by dmbarry86** [IPG-Automotive-UK/react-ui#218]
Migrate the header component that is currently part of a number of our apps over to this library and update those apps to make use of it. The code in model manager can be used as a reference point.

**Comment by akashshyamdev** [comment]
Hey, I'd like to take up this issue. Where are the "number of our apps"? There are only 2 repos(including this one) under your org.

**Comment by dmbarry86** [comment]
Hey @akashshyamdev thanks for the offer of support. The majority of our apps are private to our organisation members only. On this occassion I think a member from our organisation would need to implement this task as only they have access to the source code containing the component we would like migrating to this library. Thank you for the kind offer though.

**Comment by akashshyamdev** [comment]
Oh ok thanks, I thought this was public. Never mind, thanks for replying!

**Comment by dmbarry86** [comment]
Now implemented as part of AppLayout et al recently released by @m4manjesh
