### ISSUE TITLE
Swap primary and secondary pallete colors in Theme Provider 

### ISSUE THREAD

**Issue by jegasriskantha** [IPG-Automotive-UK/react-ui#391]
Swap primary and secondary pallete colors in Theme Provider. So that dark blue is now the primary color to align with IPG branding.

**Comment by dmbarry86** [comment]
Before releasing this we should do a local build and integrate it with one of our apps to check it looks good there as well as in Storybook standalone. I would suggest NGD would be a good test candidate.
