### ISSUE TITLE
Select value vs. label

### ISSUE THREAD

**Issue by mattcorner** [IPG-Automotive-UK/react-ui#447]
The select component doesn't allow a value to differ from the user displayed label. This limitation was enough for me to avoid using react-ui Select and instead reach for mui-select.

I would like to see the available options become:

Currently supported:
```["a", "b", "c"]```
```[1, 2, 3]```

Proposed addition:
```
[
    {label: "A", value: "a"},
    {label: "B", value: "b"},
    {label: "C", value: "c"},
]

**Comment by dmbarry86** [comment]
I think something like the `getOptionLabel` available on [MUI Autocomplete](https://mui.com/material-ui/api/autocomplete/) is the way to go here. I don't think changing options to an object is a good idea and would be a breaking change everywhere the component is currently used. An optional getOptionLabel prop feels better to me. Open to better suggestions though.

**Comment by mattcorner** [comment]
Yep, thats a better idea.

**Comment by dmbarry86** [comment]
Is this still valid @syedsalehinipg? I recall you making some change along these lines recently?
