### ISSUE TITLE
Allow custom styling of components

### ISSUE THREAD

**Issue by mattcorner** [IPG-Automotive-UK/react-ui#462]
_Originally posted by @mattcorner in https://github.com/IPG-Automotive-UK/react-ui/pull/461#discussion_r993784781_

There is a need to custom style components provided by react-ui. It is hard to anticipate use cases, but we agree that they exist. 

e.g. Canvas might need overflow:hidden in specific applications
e.g. NumberField might require custom styling e.g. in Instrument Designer toolbar.

To date we have several approaches:
- Provide sx prop to user. Currently this only works the top level element within a component, but we could mimic MUIs approach where it exposes componentClassNames object to allow further customisation.
- Wrap the component in a ThemeProvider that provides the custom styling where it is used. We can then target specific sub elements for styling.

**Comment by mattcorner** [comment]
I have a preference for the sx and className approach because it is more maintainable, and takes away the requirement to know the sub elements of a component. Having come back to MUI, this is one of the most noticeable improvements of the last 2 years.

With the themeprovider approach, you need to know that a .Mui-box exists etc.

**Comment by dmbarry86** [comment]
I prefer exposing specific props for specific needs rather than a catch all bail out sx style. I think it's better to abstract away MUI and provide specific props as they are needed. If we don't and we wanted to change from MUI or MUI make a breaking change (like styles to sx in 4 to 5) then every app using the component also needs to update. If instead we just have 'borderColor' prop for example then we only need to update inside react-ui if MUI change how border color is set or we switch to another library. In your overflow example in canvas, just add an overflow property.

**Comment by dmbarry86** [comment]
I can't really see why we need to provide a catch all for props we don't need yet. If a new requirement for a new prop comes along then we just add it and do a new release of the component.

**Comment by dmbarry86** [comment]
You say to date we have two approaches. Do we actually have any components that expose sx prop at the moment? Excluding your canvas and canvas item as they are not merged yet. Would be good to see what other components are doing this and understand why and how they are being used.

**Comment by dmbarry86** [comment]
We have had this discussion in the team before and we agreed not to expose sx (or style as it was back then in MUI4). Appreciate you weren't in the team at the time.

https://github.com/IPG-Automotive-UK/react-ui/pull/341#discussion_r798329188

**Comment by mattcorner** [comment]
I don't mind adding props to components as we need them generally e.g. the overflow, border, etc examples mentioned.

That doesn't handle the current styling use cases in ID though.

I don't think the ThemeProvider approach is a good solution to need to apply styling customisation to child elements of a react-ui component. It goes back to the old MUI days where you need to know what elements make up a component to be able to change them. If I have to go and read the react-ui code to work out whats going on, then we've not provided a better developer interface and I might as well skip react-ui and use mui. 

Looking at the Instrument Designer cases, we are targeting broad types e.g. MuiTypography. What do you do when that targets too much? There is clearly a use case for something here.

I'll also raise general layout as an important use case for some thought. Do I really need to wrap every react-ui component that I want to adding padding/margin/flexbox props to in a wrapper div? Thats not a great pattern. We should be making it easier to layout our own components rather than harder.

I've pulled the sx approach from the Canvas/CanvasItem PR as I'm not actually using it. I was just trying to cater for some of the above points in the future but appreciate I didn't feel the style > sx pain and wasn't aware of the discussion.

**Comment by dmbarry86** [comment]
@lukemojo probably worth considering these slightly old discussions when it comes to planning more about the future component library requirements as we spoke about in the knowledge share earlier today.
