### ISSUE TITLE
Code not getting minified in production bundle

### ISSUE THREAD

**Issue by dmbarry86** [IPG-Automotive-UK/react-ui#51]
Apps that use this library seem to have a copy of the source code included rather than minified version included in the bundle as with other dependencies. Is this expected?

For example, model manager source.
![image](https://user-images.githubusercontent.com/8976377/100536882-7f872080-321b-11eb-8e15-72d1c384f4f0.png)

**Comment by mattcorner** [comment]
After a bit of research, this isn't actually the case. 

See screenshot showing build files served from docker:
![image](https://user-images.githubusercontent.com/27866636/100610855-57292000-3308-11eb-9928-7f2d236b6168.png)

Folders in chrome dev tools shown in orange are actually source code parsed from the minified bundles using javascript source maps (generated by webpack). You can confirm this by disabling javascript source maps in chrome dev tools console. If you want in the future, this is something that can be turned off in production CRA builds

https://create-react-app.dev/docs/advanced-configuration/

**Comment by mattcorner** [comment]
A bit of further discussion on whether to include in production.

https://css-tricks.com/should-i-use-source-maps-in-production/

**Comment by dmbarry86** [comment]
I don't think we should include in production.
