### ISSUE TITLE
Add filter component

### ISSUE THREAD

**Issue by dmbarry86** [IPG-Automotive-UK/react-ui#53]
Migrate the filter component currently used in a number of our apps to this library.

![image](https://user-images.githubusercontent.com/8976377/100537248-a2ff9a80-321e-11eb-9838-fefd373f33fb.png)

**Comment by mattcorner** [comment]
@dmbarry86 Do you plan to move all the apps filters over to the latest new filter in VPM? If so, that should be the filter component we take for the starting point of this. 

I imagine a suite of components in that case, probably:
* Filter - Parent wrapper
* FilterField - Whats rendered when filter is not open
* FilterContent - Whats rendered when the filter is open (Popper)
* ListFilter - The actual filter controls for a list
* RangeFilter - The actual filter controls for a range
* e.g.

**Comment by dmbarry86** [comment]
Yes I think so @mattcorner but implementation needs discussion. I am not sure so many components are needed.
