### ISSUE TITLE
UserMenu spacing in AppBar in Safari

### ISSUE THREAD

**Issue by mattcorner** [IPG-Automotive-UK/react-ui#72]
<img width="269" alt="Screenshot 2020-11-27 at 19 31 55" src="https://user-images.githubusercontent.com/27866636/100998190-1bce6180-3553-11eb-914b-89a60b9a34fe.png">

Suspect something to do with IconButton with Avatar as child. IconButton ripple appears in the correct place, but the Avatar does not.

**Comment by mattcorner** [comment]
Going to have to leave this one to you @dmbarry86. I don't really have anyway to test in safari. (I tried a browser emulator that gave me 10 free seconds of safari, enough to confirm the bug but not investigate 😂)

Doubt we have any customers running Apple hardware at the moment anyway so low priority.

**Comment by dmbarry86** [comment]
Issue is fixed in latest Safari release (14.0.1)
